// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TamKafadan.Models;

namespace TamKafadan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220413121853_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KonuMakale", b =>
                {
                    b.Property<int>("KonulariKonuId")
                        .HasColumnType("int");

                    b.Property<int>("MakalelerMakaleId")
                        .HasColumnType("int");

                    b.HasKey("KonulariKonuId", "MakalelerMakaleId");

                    b.HasIndex("MakalelerMakaleId");

                    b.ToTable("KonuMakale");
                });

            modelBuilder.Entity("KonuYazar", b =>
                {
                    b.Property<int>("KonulariKonuId")
                        .HasColumnType("int");

                    b.Property<int>("YazarlarYazarId")
                        .HasColumnType("int");

                    b.HasKey("KonulariKonuId", "YazarlarYazarId");

                    b.HasIndex("YazarlarYazarId");

                    b.ToTable("KonuYazar");
                });

            modelBuilder.Entity("TamKafadan.Models.Konu", b =>
                {
                    b.Property<int>("KonuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KonuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KonuId");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("TamKafadan.Models.Makale", b =>
                {
                    b.Property<int>("MakaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusuturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("MakaleId");

                    b.HasIndex("YazarId");

                    b.ToTable("Makaleler");
                });

            modelBuilder.Entity("TamKafadan.Models.Yazar", b =>
                {
                    b.Property<int>("YazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Biografi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IlkMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarAd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("YazarId");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("KonuMakale", b =>
                {
                    b.HasOne("TamKafadan.Models.Konu", null)
                        .WithMany()
                        .HasForeignKey("KonulariKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TamKafadan.Models.Makale", null)
                        .WithMany()
                        .HasForeignKey("MakalelerMakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KonuYazar", b =>
                {
                    b.HasOne("TamKafadan.Models.Konu", null)
                        .WithMany()
                        .HasForeignKey("KonulariKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TamKafadan.Models.Yazar", null)
                        .WithMany()
                        .HasForeignKey("YazarlarYazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TamKafadan.Models.Makale", b =>
                {
                    b.HasOne("TamKafadan.Models.Yazar", "Yazar")
                        .WithMany("Makaleleri")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("TamKafadan.Models.Yazar", b =>
                {
                    b.Navigation("Makaleleri");
                });
#pragma warning restore 612, 618
        }
    }
}
